theme = "congo"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 40

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true
