[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Writing"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/josephrmaxwell/"
  weight = 50
  [main.params]
    icon = "linkedin"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[footer]]
  name = "selfhostdojo.com"
  url = "https://selfhostdojo.com"
  weight = 10

[[footer]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/josephrmaxwell/"
  weight = 20
